title: Evrard-Nil Daillet
subtitle: Software Engineer Apprentice
description: >-
  Evrard-Nil Daillet's Personal Website

url: "https://evrard-nil.github.io"
baseurl: ""

urls:
  - text: About Me
    url: /about/
  - text: Projects
    url: /projects
  - text: Experience
    url: /experience
  - text: Contact Me
    url: /contact/
  # - text: Styleguide
  #   url: /styleguide/

author_logo: profile.png
author: Evrard-Nil Daillet
author_bio: Hi, my name is Evrard-Nil Daillet. I am a french student, currently in fourth year of Software Engineer's Degree at <a href = "https://www.imt-atlantique.fr/fr">'Institut Mines-Telecom Atlantique'</a>. I am seeking an intership starting in May 2020, for 9 to 14 weeks.<br> I love to play around with new technologies and software, feel free to browse some of my projects below.
author_email: "evrard-nil.daillet@gmail.com"
author_location: Nantes, France

author_work_experiences:
  - company_name: Sopra Steria
    company_logo: soprasteria.png
    company_url: https://www.soprasteria.com/en
    designation: Software Engineer Apprentice
    slug: sopra-steria
    Leveraged skills: Python, Saltstack, Unix, Networks, Infrastructure Management.
    description: Helped to build and maintain an infrastructure management solution for the CNAM (french institution) using SaltStack.<br> Developed  a  solution  testing  the  deployment  of  an  application  inside  dynamically created containers automatically allowing to decrease testing time by 50%.
    visibility: true
  - company_name: S2E (Société Générale subsidiary)
    company_logo: sg.png
    company_url: http://www.s2e-services-epargne-entreprise.com/
    designation: Software Engineer Intern
    slug: s2e
    description: Developped predictive AI model to better anticipate risky or safe period in banking environment.
    visibility: true

author_education_details:
  - college_logo: imt.png
    college_name: IMT Atlantique
    college_url: https://www.imt-atlantique.fr/en
    college_degree: Software Engineering
    description: Master of Science
    visibility: true

author_software_project_details:
  - project_thumbnail: gamershub.png
    project_slug: liyo-app
    project_info: Personal
    project_title: "Profile Picture Adviser"
    project_description: Built a micro-services backend and mobile application using Kubernetes, Go, Dart and more.
    project_url: https://github.com/evrard-nil/pic-rater
    visibility: true
  - project_thumbnail: programmingebooks.png
    project_slug: weather-data-collection
    project_info: Scholar
    project_title: Weather data collector
    project_description: Developped a weather data collector using Golang and an MQTT broker (publish-subscribe pattern).
    project_url: https://github.com/Evrard-Nil/middleware
    visibility: true
  - project_thumbnail: programmingebooks.png
    project_slug: note-taker
    project_info: Personal
    project_title: Note Taker
    project_description: Developped a small mobile application allowing users to create notes using markdown.
    project_url: https://programmingebooks.com
    visibility: true
  - project_thumbnail: programmingebooks.png
    project_slug: green-it-study
    project_info: Scholar
    project_title: Green IT study
    project_description: Studied how service design could impact ressource usage inside a micro-services environment.
    project_url: https://programmingebooks.com
    visibility: true

author_add_expereience_details:
  - project_thumbnail: programmingebooks.png
    project_slug: mentorship
    project_info: Personal
    project_title: Mentorship
    project_description: Taught first-year student students about Math, Physics, Mecanics or Computer Science.
    project_url: https://programmingebooks.com
    visibility: true
  - project_thumbnail: programmingebooks.png
    project_slug: scout-leader
    project_info: Personal
    project_title: Scout Leader
    project_description: Lead a team of 6 to 8 scouts during 2 years. Organised, planned and budgeted activities.
    project_url: https://programmingebooks.com
    visibility: true

github_username: evrard-nil
linkedin_username: endaillet
wakatime_username: Evrard

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10

show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]

collections_dir: collections
collections:
  experience:
    output: True
    permalink: /:collection/:title
  projects:
    output: True
    permalink: /:collection/:title
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
